# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Galeria Kaufhof Technology Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: galeriakaufhof
github_username:  Galeria-Kaufhof

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

author :
  name : GALERIA Kaufhof GmbH
  email : manuel.kiessling@kaufhof.de
  github : Galeria-Kaufhof
  twitter : galeriakaufhof

authors:
  manuelkiessling:
    display_name: Manuel Kiessling
    gravatar: 8b50d5d8199a12f00cfbfd1061e224a9
    email: manuel.kiessling@kaufhof.de
    web: http://manuel.kiessling.net
    twitter: manuelkiessling
    github: manuelkiessling

  martingrotzke:
    display_name: Martin Grotzke
    gravatar: 4e1908b60857ac6d68a27e82016b9843
    email: martin.grotzke@inoio.de
    web: http://www.inoio.de
    twitter: martin_grotzke
    github: magro

  janalgermissen:
    display_name: Jan Algermissen
    gravatar: ec21ce28e9a469b3eb148daad9935c89
    email: jan.algermissen@talentformation.com
    web: http://algermissen.blogspot.de
    twitter: algermissen
    github: algermissen

  ricopfaus:
    display_name: Rico Pfaus
    gravatar: c2e07ac6111335e525da4c889b3b2c0c
    email: rico.pfaus@kaufhof.de
    twitter: ryxxxx
    github: ryx


# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://galeria-kaufhof.github.io

rss_path : /rss.xml
atom_path : /atom.xml

disqus:
  short_name: galeriakaufhoftechnologyblog